language: php
php:
  - 5.4
  - 5.3

env:
  - JVERSION_TEST=3.x

before_script:
  - sudo pear upgrade PEAR
  - pear config-set auto_discover 1
  - pear install phpunit/DbUnit
  - pear install pear.phpunit.de/PHPUnit
  - mysql -e 'create database fof_test;'
  - mysql -e 'USE fof_test;'
  - if [[ "$JVERSION_TEST" == "2.5" ]]; then cp tests/environments/2.5/joomla.sql joomla.sql; fi
  - if [[ "$JVERSION_TEST" == "3.x" ]]; then cp tests/environments/3.x/joomla.sql joomla.sql; fi
  - mysql -u travis --password= -h 127.0.0.1 fof_test < joomla.sql
  - cp build/templates/include.php fof/include.php

notifications:
  email: false

script: phpunit --bootstrap=tests/unit/bootstrap.php tests