language: php
php:
  - 5.4
  - 5.3

env:
  - JVERSION_TEST=3.x

before_script:
  - mysql -e 'create database fof_test;'
  - mysql -e 'USE fof_test;'
  - cp tests/environments/$JVERSION_TEST/joomla.sql joomla.sql
  - mysql -u travis --password= -h 127.0.0.1 fof_test < joomla.sql

script: phpunit --bootstrap=tests/unit/bootstrap.php tests
